theme: jekyll-theme-leap-day
title: Lazy Results
description: Jackson 2.x datatype module for Result
current_version: 1.0.3.0
show_downloads: true
logo: https://dev.leakyabstractions.com/result/result-banner.png
exclude:
  - gradle
  - result-jackson
